### ISSUE TITLE
Gradle / Maven tabs produce a jump to some other location in the docs

### ISSUE THREAD

**Issue by lukaseder** [micronaut-projects/micronaut-docs#12]
There are a lot of Gradle / Maven tabs in your docs (which is a great feature, btw), which lead to the documentation jumping elsewhere in Google Chrome 77.0.3865.90 as well as in Firefox. Here's a recording of how this behaves in Chrome:

![image](https://i.imgur.com/2egzl4u.gif)

**Comment by graemerocher** [comment]
Thanks I think we have this fixed in the main docs (https://docs.micronaut.io/latest/guide/index.html#ideSetup) but we need to propagate the change to some of the subprojects like the SQL one

**Comment by lukaseder** [comment]
Cool, thanks. Yes, I can confirm, in that link you posted, I don't see that problem.

**Comment by JoshuaCWebDeveloper** [comment]
This issue is still happening for me on Edge at https://docs.micronaut.io/latest/guide/index.html. This also happens when clicking on the Java / Groovy code tabs (presumably the same issue).

**Comment by graemerocher** [comment]
interesting, I can reproduce in Safari actually. Doesn't happen on Firefox or Chrome for the Mac

**Comment by niravassar** [comment]
I tested on windows microsoft edge and the problem exists. On windows firefox and chrome i dont have the problem

**Comment by sdelamo** [comment]
This is the current status: 

![Old](https://user-images.githubusercontent.com/864788/70610894-a3191b80-1c04-11ea-9611-fe195b90dcf0.gif)

with `scrollIntoView` and slight offset I think the effect is better. 

https://github.com/micronaut-projects/micronaut-docs/commit/0d2e04f48513b09a317f32f3a937fb55052138b9

![New](https://user-images.githubusercontent.com/864788/70611070-ea071100-1c04-11ea-9157-dc11abe7d8b8.gif)


It is not perfect but since code snippets block change in the whole page and they have different lengths I don't know if we can achieve a better outcome.

**Comment by sdelamo** [comment]
I am going to close this issue. I encourage anyone still experiencing issues to reopen.
